### ISSUE TITLE
Vercel Deployment fails

### ISSUE THREAD

**Issue by JensWinter** [technologiestiftung/giessdenkiez-de-postgres-api#212]
Deploying on Vercel fails because the pages directory is missing. Anyone experiences this too?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/6548550/228651336-bc6888a4-0f30-4199-81fb-c9ae9eede3c7.png">

Adding an empty pages folder (containing just a .gitkeep file) works, though. But I'm not sure if this the correct solution. Maybe there is a Vercel or Next configuration I am missing.

**Comment by ff6347** [comment]
Can you have a look what your `Build & Development Settings` for your project are? I guess it is set to Next.js? 
![Screenshot 2023-03-29 at 22-19-31 Project Settings – Dashboard – Vercel](https://user-images.githubusercontent.com/315106/228658188-15e22895-4e7a-478b-bd1d-92eb429c8ce3.png)

**Comment by JensWinter** [comment]
Ah! You are correct. Thank you! I guess that's it. Gonna try it out.

**Comment by JensWinter** [comment]
Yep. I can confirm. That helped. :)
